site_name: 白杨的文档站
site_url: https://whiteboard-ui8.pages.dev/
site_description: 本站用于收纳站长的一些杂谈、笔记和博客等内容。
site_author: Poplar at twilight

repo_name: SRC
repo_url: https://github.com/poplar-at-twilight/whiteboard
edit_uri: ""

theme:
    name: material
    language: zh    
    #custom_dir: overrides
    highlightjs: true
    palette:
    # Palette toggle for light mode
      - media: "(prefers-color-scheme: light)"
        scheme: default
        primary: white
        accent: red
        toggle:
          icon: material/weather-night
          name: Switch to dark mode
    # Palette toggle for dark mode
      - media: "(prefers-color-scheme: dark)"
        scheme: slate
        primary: black
        accent: red
        toggle:
          icon: material/weather-sunny
          name: Switch to light mode
    features:
      - navigation.tabs
      - content.tabs.link #启用内容页
      - navigation.footer
      - header.autohide  #公告栏
      - announce.dismiss #可关闭的公告栏
    logo: assets/greyweb.svg
    icon:
      repo: fontawesome/brands/github
    font:
      text: Noto Sans
      code: Noto Sans Mono    

nav:
    - 首页:
      - index.md
      - tags.md
    - 站内杂谈: 
      - essay/about.md
      - 杂谈:
        - essay/others/qbittorrent-conf.md
        - essay/others/aria2.md
        - essay/others/md-epub.md
        - essay/others/ainme.md
        - essay/others/play-minecraft.md
        - essay/others/use-rss-sub.md
        - essay/others/adjust-win11-for-popurse.md
        - essay/others/2021-08.md
        - essay/others/opencc.md
        - essay/others/alias-tips.md
        - essay/others/eyecandy-kde.md
        - essay/others/python-embed.md
      - 随笔&日常:
        - essay/main/about.md
        #- essay/main/
        - essay/main/misc.md
      - 笔记:
        - essay/note/about.md
        - essay/note/preparation.md
        - essay/note/installation.md
        - essay/note/first-boot.md
        - essay/note/software.md
        - essay/note/kde.md
        - essay/note/fonts.md
        - essay/note/re-install.md
        - essay/note/shell-script.md
    - 站外归档:
      - archives/about.md
      - archives/external-index.md
      - archives/pandoc's-markdwon-spec.md
      - 博客归档:
        - archives/qbittorrent-confs.md
        - archives/rss-refresh.md
    - 博客:
      - blog/index.md
    - 关于: 
      - about/about-me.md
      - about/friends.md
      - about/license.md

markdown_extensions:
  #启用工具提示
  - abbr
  - attr_list
  - pymdownx.snippets
  #启用警示标识
  - admonition
  - pymdownx.details
  - pymdownx.superfences 
  #启用注释
  - attr_list
  - md_in_html
  - pymdownx.superfences
  #启用按钮
  - attr_list
  #启用内容页
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  #启用脚注
  - footnotes
  #启用文本格式化
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  #启用图片
  - attr_list
  - md_in_html
  #启用列表
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

plugins:
  - search #启用搜索
  - blog:   #启用博客
      blog_toc: true
      authors_file: blog/.authors.yml
      post_readtime: false
  - tags:
      tags_file: tags.md
  - rss:
      abstract_chars_count: -1
      match_path: blog/posts/.* 
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags

extra:
  social:
    - icon: fontawesome/brands/suse
      link: https://forum.suse.org.cn/u/Aui/summary
    - icon: fontawesome/brands/fedora
      link: https://discussion.fedoraproject.org/u/bh
    - icon: fontawesome/brands/wikipedia-w
      link: https://zh.opensuse.org/User:White-poplar
    - icon: fontawesome/brands/github
      link: https://github.com/poplar-at-twilight

copyright: Copyleft; 2021-2024 Poplar_at_twilight